import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { exec } from "../utils/exec.js";
import type { Manifest } from "./manifest.js";

// ---------------------------------------------------------------------------
// Official skill repos — installed via `npx skills add`
// ---------------------------------------------------------------------------

interface SkillSource {
  repo: string;
  skill: string;
}

/** Map of database/feature provider → official agent skills to install */
const PROVIDER_SKILLS: Record<string, SkillSource[]> = {
  neon: [
    { repo: "https://github.com/neondatabase/agent-skills", skill: "neon-postgres" },
    { repo: "https://github.com/neondatabase/ai-rules", skill: "neon-serverless" },
  ],
  supabase: [
    { repo: "https://github.com/supabase/agent-skills", skill: "supabase-postgres-best-practices" },
  ],
  "prisma-postgres": [
    // Prisma skill is typically bundled in the template already
  ],
};

/**
 * Install official provider skills via `npx skills add`.
 * Runs in the project directory. Non-blocking — failures are warnings, not errors.
 */
export function installProviderSkills(projectDir: string, provider: string): void {
  const skills = PROVIDER_SKILLS[provider];
  if (!skills || skills.length === 0) return;

  for (const { repo, skill } of skills) {
    const result = exec(
      `npx -y skills add ${repo} --skill ${skill}`,
      projectDir,
    );
    if (!result.success) {
      // Non-fatal — skills are nice-to-have
      console.log(`  (Could not install ${skill} skill — you can add it later)`);
    }
  }
}

// ---------------------------------------------------------------------------
// Project context — auto-generated description of what's configured
// ---------------------------------------------------------------------------

/**
 * Generate a project-specific context file that tells AI coding assistants
 * what's configured in this project. Like Stripe's project-context.md.
 */
export function writeProjectContext(
  projectDir: string,
  manifest: Manifest,
  envVars: Record<string, boolean>,
): void {
  const dir = join(projectDir, ".whop");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const lines: string[] = [
    "# Project Context",
    "",
    "Auto-generated by create-whop-kit. Helps AI coding assistants understand",
    "your project. Regenerated by `whop-kit status`. Do not edit manually.",
    "",
    "## Project",
    "",
    `- **Framework:** ${manifest.framework}`,
    `- **App Type:** ${manifest.appType}`,
    `- **Database:** ${manifest.database}`,
    `- **Template Version:** ${manifest.templateVersion}`,
    `- **Created:** ${manifest.createdAt}`,
    "",
    "## Configuration Status",
    "",
  ];

  const checks = [
    ["DATABASE_URL", "Database", true],
    ["NEXT_PUBLIC_WHOP_APP_ID", "Whop App ID", true],
    ["WHOP_API_KEY", "Whop API Key", true],
    ["WHOP_WEBHOOK_SECRET", "Webhook Secret", true],
    ["EMAIL_PROVIDER", "Email", false],
    ["ANALYTICS_PROVIDER", "Analytics", false],
  ] as const;

  for (const [key, label, required] of checks) {
    const set = envVars[key] ?? false;
    const icon = set ? "✓" : required ? "✗" : "○";
    lines.push(`- ${icon} ${label} (\`${key}\`)`);
  }

  if (manifest.features.length > 0) {
    lines.push("");
    lines.push("## Installed Features");
    lines.push("");
    for (const feature of manifest.features) {
      lines.push(`- ${feature}`);
    }
  }

  lines.push("");
  lines.push("## Key Files");
  lines.push("");

  if (manifest.framework === "nextjs") {
    lines.push("- `lib/auth.ts` — session management (whop-kit/auth)");
    lines.push("- `lib/adapters/next.ts` — Next.js cookie adapter");
    lines.push("- `lib/adapters/prisma.ts` — Prisma DB + config adapters");
    lines.push("- `app/api/webhooks/whop/route.ts` — webhook handler");
    lines.push("- `app/api/auth/` — OAuth login/callback/logout");
    lines.push("- `db/schema.prisma` — database schema");
  } else if (manifest.framework === "astro") {
    lines.push("- `src/lib/auth.ts` — session management (whop-kit/auth)");
    lines.push("- `src/lib/adapters/astro.ts` — Astro cookie adapter");
    lines.push("- `src/lib/adapters/prisma.ts` — Prisma DB adapter");
    lines.push("- `src/pages/api/webhooks/whop.ts` — webhook handler");
    lines.push("- `src/pages/api/auth/` — OAuth login/callback/logout");
  }

  lines.push("");
  lines.push("## CLI Commands");
  lines.push("");
  lines.push("```bash");
  lines.push("npx whop-kit status        # check project health");
  lines.push("npx whop-kit add email     # add email provider");
  lines.push("npx whop-kit add analytics # add analytics");
  lines.push("npx whop-kit catalog       # list available services");
  lines.push("npx whop-kit open whop     # open Whop dashboard");
  lines.push("npx whop-kit upgrade       # update whop-kit");
  lines.push("```");
  lines.push("");

  writeFileSync(join(dir, "project-context.md"), lines.join("\n"));
}

// ---------------------------------------------------------------------------
// Feature-specific skill writing (for features without official repos)
// ---------------------------------------------------------------------------

/**
 * Write a provider-specific skill when a feature is added.
 * Only for providers that don't have an official agent-skills repo.
 */
export function writeFeatureSkill(
  projectDir: string,
  featureKey: string,
  provider: string,
): void {
  const dir = join(projectDir, ".agents", "skills", "whop-kit-features");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const content = generateFeatureSkill(featureKey, provider);
  if (content) {
    writeFileSync(join(dir, `${featureKey}-${provider}.md`), content);
  }
}

function generateFeatureSkill(featureKey: string, provider: string): string | null {
  const key = `${featureKey}:${provider}`;

  const skills: Record<string, string> = {
    "email:resend": `---
name: resend-email
description: Resend transactional email integration. Use when working with email sending, templates, or email configuration.
---

# Resend Email

This project uses Resend for transactional email via whop-kit/email.

## Usage
\`\`\`typescript
import { sendEmail } from "@/lib/email";
await sendEmail({ to: "user@example.com", subject: "Hello", html: "<p>Hi!</p>" });
\`\`\`

## Config
- \`EMAIL_PROVIDER=resend\`
- \`EMAIL_API_KEY\` — Resend API key
- \`EMAIL_FROM_ADDRESS\` — verified sender

## Templates
Edit \`lib/email-templates.ts\`. Each function returns \`{ subject, html }\`.

## Dashboard
https://resend.com/overview
`,

    "email:sendgrid": `---
name: sendgrid-email
description: SendGrid transactional email integration. Use when working with email sending, templates, or email configuration.
---

# SendGrid Email

This project uses SendGrid for transactional email via whop-kit/email.

## Usage
\`\`\`typescript
import { sendEmail } from "@/lib/email";
await sendEmail({ to: "user@example.com", subject: "Hello", html: "<p>Hi!</p>" });
\`\`\`

## Config
- \`EMAIL_PROVIDER=sendgrid\`
- \`EMAIL_API_KEY\` — SendGrid API key
- \`EMAIL_FROM_ADDRESS\` — verified sender

## Dashboard
https://app.sendgrid.com
`,

    "analytics:posthog": `---
name: posthog-analytics
description: PostHog product analytics integration. Use when working with analytics, events, or feature flags.
---

# PostHog Analytics

Injected via whop-kit/analytics \`getAnalyticsScript()\`. No client SDK needed.

## Config
- \`ANALYTICS_PROVIDER=posthog\`
- \`ANALYTICS_ID\` — project API key (phc_xxx)

## Dashboard
https://us.posthog.com
`,

    "analytics:google": `---
name: google-analytics
description: Google Analytics 4 integration.
---

# Google Analytics 4

Injected via whop-kit/analytics \`getAnalyticsScript()\`.

## Config
- \`ANALYTICS_PROVIDER=google\`
- \`ANALYTICS_ID\` — measurement ID (G-XXXXXXXXXX)

## Dashboard
https://analytics.google.com
`,

    "analytics:plausible": `---
name: plausible-analytics
description: Plausible privacy-friendly analytics integration.
---

# Plausible Analytics

Injected via whop-kit/analytics \`getAnalyticsScript()\`. No cookies, GDPR compliant.

## Config
- \`ANALYTICS_PROVIDER=plausible\`
- \`ANALYTICS_ID\` — your domain

## Dashboard
https://plausible.io/sites
`,
  };

  return skills[key] ?? null;
}
